import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/Home/Footer";

const font = Poppins({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.className}>
      <body className="flex flex-col justify-start items-center w-full min-h-screen">
        <NavBar />
        <main className="w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
